### ISSUE TITLE
Multiple CSS issues for ordered lists

### ISSUE THREAD

**Issue by krystian-hebel** [3mdeb/news-and-ideas#172]
See e.g. https://blog.3mdeb.com/2019/2019-04-30-5-terms-every-hypervisor-developer-should-know/#vm-entries

- list items are centered instead of left-aligned
- if list items are short enough, multiple items are in the same line due to floating
- line height is hardcoded, multi-line items are written on top of the next one

**Comment by lukasz-matysiewicz** [comment]
https://github.com/3mdeb/news-and-ideas/pull/174 fix
