### ISSUE TITLE
new-post.sh add TABs to the tag list instead of two spaces

### ISSUE THREAD

**Issue by miczyg1** [3mdeb/news-and-ideas#186]
https://github.com/3mdeb/news-and-ideas/blob/master/scripts/new-post.sh#L33

adds hard TABs before each tag. On many posts, I have seen that tags and categories are started with two spaces. What is the right formatting for the header?

**Comment by artur-rs** [comment]
@miczyg1 yeah, yaml files can be sensitive about hard tabs - fix https://github.com/3mdeb/news-and-ideas/pull/187
