### ISSUE TITLE
Websitevoice icon overlaps the top panel

### ISSUE THREAD

**Issue by miczyg1** [3mdeb/news-and-ideas#196]
https://blog.3mdeb.com/2020/2020-02-05-meta-pcengines-xen/

**Comment by miczyg1** [comment]
![Screenshot from 2020-02-06 10-08-31](https://user-images.githubusercontent.com/30656491/73923978-01dcd780-48cc-11ea-8f83-c39f69840470.png)

**Comment by artur-rs** [comment]
fix: https://github.com/3mdeb/news-and-ideas/pull/239
