### ISSUE TITLE
Menu not visible/not fully visible at exact resolution/ranges

### ISSUE THREAD

**Issue by artur-rs** [3mdeb/news-and-ideas#482]
* __web browser__: `Chrome Version 99.0.4844.51 (Official Build) (64-bit)` and `Mozilla 98.0.1 (64-bit)`
* __description__: Menu is either not visible on 1101x938 [screenshot1] or cropped from 1102x938 to 1239x1063 [screenshot2]
* __expected behaviour__: responsive menu without any cropped areas, mobile to desktop view should switch without any dead ranges specified above

1. Screenshot1 - 1101x938: ![](https://cloud.3mdeb.com/index.php/s/YQzewMao3HR3TyR/preview)
2. Screenshot2 - from 1102x938 to 1239x1063: ![](https://cloud.3mdeb.com/index.php/s/g8et9fgzG8roA3X/preview)

**Comment by pietrushnic** [comment]
Also I wonder if any standard screen resolution is affected, maybe this is minor issue? In google analytics we have just mobile screen resolutions, all of them trigger hamburger menu.

**Comment by pietrushnic** [comment]
@artur-rs, is this still a valid bug report?
