### ISSUE TITLE
Non-interactive hamburger menu

### ISSUE THREAD

**Issue by artur-rs** [3mdeb/news-and-ideas#483]
* __web browser__: `Chrome Version 99.0.4844.51 (Official Build) (64-bit)` and `Mozilla 98.0.1 (64-bit)`
* __description__: Hamburger menu that is visible in the mobile menu is not clickable (works only in the developer tools mode in Chrome for example)
* __expected behaviour__: Mobile version on desktops works correctly, hamburger menu rolls-up as intended

**Comment by pietrushnic** [comment]
@artur-rs I don't understand this report. I though inspect/developer tools mode is the way to test mobile view. How you trigger mobile menu without mobile mode on desktop?

**Comment by artur-rs** [comment]
@pietrushnic to be more precise, the problem was triggered in the desktop view (small window), when for example we need to split the desktop to two browser windows for multitasking

**Comment by pietrushnic** [comment]
@artur-rs, this seems to be solved. Can you confirm?

**Comment by artur-rs** [comment]
@pietrushnic I cannot reproduce the problem.
