### ISSUE TITLE
Support for Reddit, Mastodon and Matrix profiles in blog post authors

### ISSUE THREAD

**Issue by pietrushnic** [3mdeb/news-and-ideas#550]
Currently we support: facebook, twitter, linkedin, github

We should try to support all six platforms 3mdeb make announcements: facebook, twitter, linkedin, reddit, mastodon, matrix

**Comment by pietrushnic** [comment]
@BeataZdunczyk @artur-rs, please confirm all members of EFT and EST added descriptions and links to profiles that they would like to promote.

**Comment by BeataZdunczyk** [comment]
@pietrushnic I can't confirm. We currently have two PRs awaiting merging:
- https://github.com/3mdeb/news-and-ideas/pull/573
- https://github.com/3mdeb/news-and-ideas/pull/549

Additionally, two EFT members have not yet submitted their PR with profile updates.

**Comment by pietrushnic** [comment]
@artur-rs how many EST members completed their profiles?

**Comment by artur-rs** [comment]
@pietrushnic all members of the current EST

**Comment by pietrushnic** [comment]
@artur-rs thanks.

**Comment by artur-rs** [comment]
@pietrushnic should I add support in Hugo for new services mentioned above?

**Comment by pietrushnic** [comment]
@artur-rs I don't know how hard it is and I'm pretty sure there are higher priorities right now. If this is not big thing and you will have time sure, you can add it.

**Comment by artur-rs** [comment]
@pietrushnic implemented here: https://github.com/3mdeb/news-and-ideas/pull/575

**Comment by BeataZdunczyk** [comment]
@pietrushnic all developers in the EFT have updated their profiles.

**Comment by pietrushnic** [comment]
@BeataZdunczyk thank you.
