### ISSUE TITLE
There are still places where "3mdeb Embedded System Condulting" is used, we should fix that

### ISSUE THREAD

**Issue by pietrushnic** [3mdeb/news-and-ideas#584]
On the bottom of https://blog.3mdeb.com/2021/2021-12-03-rockchip-secure-boot/

> 2023 3mdeb Embedded Systems Consulting | All rights reserved.

Also, we have to update the copyright. Please let me know if you know how to fix that

**Comment by Stanislaw-bnk** [comment]
I've updated the footer: https://github.com/3mdeb/news-and-ideas/pull/585. 
Unfortunately the linkChecker detected some errors on the blog, will have to find and fix them.

**Comment by artur-rs** [comment]
@Stanislaw-bnk merged, the SEO errors will be fixed on `develop`, thanks.
@pietrushnic `Also, we have to update the copyright` - please check if PR addressed everything you mentioned

**Comment by pietrushnic** [comment]
@artur-rs copyright notice need year

**Comment by Stanislaw-bnk** [comment]
I've asked Marta about that, she suggested to delete the year next to the copyright.

**Comment by pietrushnic** [comment]
OK, then I will not argue with legal experts.
