### ISSUE TITLE
Deprecated GitHub Actions artifacts

### ISSUE THREAD

**Issue by m-iwanicki** [3mdeb/news-and-ideas#604]
Failing workflow:
https://github.com/3mdeb/news-and-ideas/actions/runs/10993516959/job/30520142282?pr=593

> Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/

Quoting this link:

> With the introduction of v4, we will be deprecating v1 and v2 of actions/upload-artifact, actions/download-artifact, and related npm packages on June 30, 2024.
> [...] However, attempting to use a version of the actions after the announced deprecation date will result in a workflow failure

**Comment by artur-rs** [comment]
@m-iwanicki thanks for a quick fix
